# Set up package options
set(CPACK_PACKAGE_NAME "tvr-core")
set(CPACK_PACKAGE_VENDOR "Tencent, Inc.")
set(CPACK_PACKAGE_CONTACT "<support@tvr.com>")
set(CPACK_PACKAGE_VERSION_MAJOR 0)
set(CPACK_PACKAGE_VERSION_MINOR 1)
set(TVR_VERSION ${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION ${TVR_VERSION})
